# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Camera(object):
    def setupUi(self, Camera):
        Camera.setObjectName("Camera")
        Camera.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Camera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.previewLabel = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewLabel.sizePolicy().hasHeightForWidth())
        self.previewLabel.setSizePolicy(sizePolicy)
        self.previewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_2.addWidget(self.previewLabel)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.formWidget = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.formWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.brightnessLabel = QtWidgets.QLabel(self.formWidget)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.verticalLayout_3.addWidget(self.brightnessLabel)
        self.brightnessSlider = QtWidgets.QSlider(self.formWidget)
        self.brightnessSlider.setMinimum(-1)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.verticalLayout_3.addWidget(self.brightnessSlider)
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.contrastLabel = QtWidgets.QLabel(self.formWidget)
        self.contrastLabel.setObjectName("contrastLabel")
        self.verticalLayout_3.addWidget(self.contrastLabel)
        self.contrastSlider = QtWidgets.QSlider(self.formWidget)
        self.contrastSlider.setMinimum(-1)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.verticalLayout_3.addWidget(self.contrastSlider)
        self.label_4 = QtWidgets.QLabel(self.formWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.gainLabel = QtWidgets.QLabel(self.formWidget)
        self.gainLabel.setObjectName("gainLabel")
        self.verticalLayout_3.addWidget(self.gainLabel)
        self.gainSlider = QtWidgets.QSlider(self.formWidget)
        self.gainSlider.setMinimum(-1)
        self.gainSlider.setMaximum(100)
        self.gainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gainSlider.setObjectName("gainSlider")
        self.verticalLayout_3.addWidget(self.gainSlider)
        self.horizontalLayout.addWidget(self.formWidget)
        self.verticalLayout_4.addWidget(self.widget1)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveAsButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.saveAsButton.setObjectName("saveAsButton")
        self.verticalLayout_5.addWidget(self.saveAsButton)
        self.saveButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_5.addWidget(self.saveButton)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Camera)
        self.brightnessSlider.valueChanged['int'].connect(self.brightnessLabel.setNum)
        self.contrastSlider.valueChanged['int'].connect(self.contrastLabel.setNum)
        self.gainSlider.valueChanged['int'].connect(self.gainLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(Camera)

    def retranslateUi(self, Camera):
        _translate = QtCore.QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Camera"))
        self.previewLabel.setText(_translate("Camera", "Camera loading or not available"))
        self.label_2.setText(_translate("Camera", "Brightness"))
        self.brightnessLabel.setText(_translate("Camera", "TextLabel"))
        self.label_3.setText(_translate("Camera", "Contrast"))
        self.contrastLabel.setText(_translate("Camera", "TextLabel"))
        self.label_4.setText(_translate("Camera", "Gain"))
        self.gainLabel.setText(_translate("Camera", "TextLabel"))
        self.saveAsButton.setText(_translate("Camera", "Save As..."))
        self.saveButton.setText(_translate("Camera", "Save"))

