# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Camera(object):
    def setupUi(self, Camera):
        Camera.setObjectName("Camera")
        Camera.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Camera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previewLabel = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewLabel.sizePolicy().hasHeightForWidth())
        self.previewLabel.setSizePolicy(sizePolicy)
        self.previewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.horizontalLayout.addWidget(self.previewLabel)
        self.formWidget = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.formWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.formWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.roiButton = QtWidgets.QRadioButton(self.groupBox)
        self.roiButton.setChecked(True)
        self.roiButton.setObjectName("roiButton")
        self.verticalLayout_2.addWidget(self.roiButton)
        self.zoomButton = QtWidgets.QRadioButton(self.groupBox)
        self.zoomButton.setObjectName("zoomButton")
        self.verticalLayout_2.addWidget(self.zoomButton)
        self.zoomResetButton = QtWidgets.QPushButton(self.groupBox)
        self.zoomResetButton.setObjectName("zoomResetButton")
        self.verticalLayout_2.addWidget(self.zoomResetButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.brightnessLabel = QtWidgets.QLabel(self.formWidget)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.verticalLayout_3.addWidget(self.brightnessLabel)
        self.brightnessSlider = QtWidgets.QSlider(self.formWidget)
        self.brightnessSlider.setMinimum(-1)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.verticalLayout_3.addWidget(self.brightnessSlider)
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.contrastLabel = QtWidgets.QLabel(self.formWidget)
        self.contrastLabel.setObjectName("contrastLabel")
        self.verticalLayout_3.addWidget(self.contrastLabel)
        self.contrastSlider = QtWidgets.QSlider(self.formWidget)
        self.contrastSlider.setMinimum(-1)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.verticalLayout_3.addWidget(self.contrastSlider)
        self.label_4 = QtWidgets.QLabel(self.formWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.gainLabel = QtWidgets.QLabel(self.formWidget)
        self.gainLabel.setObjectName("gainLabel")
        self.verticalLayout_3.addWidget(self.gainLabel)
        self.gainSlider = QtWidgets.QSlider(self.formWidget)
        self.gainSlider.setMinimum(-1)
        self.gainSlider.setMaximum(100)
        self.gainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gainSlider.setObjectName("gainSlider")
        self.verticalLayout_3.addWidget(self.gainSlider)
        self.rotatePushButton = QtWidgets.QPushButton(self.formWidget)
        self.rotatePushButton.setObjectName("rotatePushButton")
        self.verticalLayout_3.addWidget(self.rotatePushButton)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.flipUDLabel = QtWidgets.QLabel(self.formWidget)
        self.flipUDLabel.setObjectName("flipUDLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.flipUDLabel)
        self.flipUDCheckBox = QtWidgets.QCheckBox(self.formWidget)
        self.flipUDCheckBox.setObjectName("flipUDCheckBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.flipUDCheckBox)
        self.flipLRLabel = QtWidgets.QLabel(self.formWidget)
        self.flipLRLabel.setObjectName("flipLRLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.flipLRLabel)
        self.flipLRCheckBox = QtWidgets.QCheckBox(self.formWidget)
        self.flipLRCheckBox.setObjectName("flipLRCheckBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.flipLRCheckBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.formWidget)
        self.verticalLayout_4.addWidget(self.widget1)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveAsButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.saveAsButton.setObjectName("saveAsButton")
        self.verticalLayout_5.addWidget(self.saveAsButton)
        self.saveButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_5.addWidget(self.saveButton)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Camera)
        self.brightnessSlider.valueChanged['int'].connect(self.brightnessLabel.setNum)
        self.contrastSlider.valueChanged['int'].connect(self.contrastLabel.setNum)
        self.gainSlider.valueChanged['int'].connect(self.gainLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(Camera)

    def retranslateUi(self, Camera):
        _translate = QtCore.QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Camera"))
        self.previewLabel.setText(_translate("Camera", "Camera loading or not available"))
        self.groupBox.setTitle(_translate("Camera", "Selection Mode"))
        self.roiButton.setText(_translate("Camera", "ROI"))
        self.zoomButton.setText(_translate("Camera", "Zoom"))
        self.zoomResetButton.setText(_translate("Camera", "Reset Zoom"))
        self.label_2.setText(_translate("Camera", "Brightness"))
        self.brightnessLabel.setText(_translate("Camera", "TextLabel"))
        self.label_3.setText(_translate("Camera", "Contrast"))
        self.contrastLabel.setText(_translate("Camera", "TextLabel"))
        self.label_4.setText(_translate("Camera", "Gain"))
        self.gainLabel.setText(_translate("Camera", "TextLabel"))
        self.rotatePushButton.setText(_translate("Camera", "Rotate 90°"))
        self.flipUDLabel.setText(_translate("Camera", "Flip UD"))
        self.flipLRLabel.setText(_translate("Camera", "Flip LR"))
        self.saveAsButton.setText(_translate("Camera", "Save As..."))
        self.saveButton.setText(_translate("Camera", "Save"))

